- name: install java
  apt: name=openjdk-7-jre state=present update_cache=yes

- name: add cassandra debian repository
  apt_repository: repo='deb http://www.apache.org/dist/cassandra/debian 21x main' state=present

- name: add the key for the cassandra debian repo
  apt_key: keyserver=pgp.mit.edu id=F758CE318D77295D

- name: add the other key for cassandra
  apt_key: keyserver=pgp.mit.edu id=2B5C1B00

- name: install cassandra
  apt: name=cassandra state=present update_cache=yes force=yes

- name: override cassandra.yaml file
  template: src=cassandra.yaml dest=/etc/cassandra/

- name: make sure cassandra is started
  service: name=cassandra state=restarted

- name: alias spark shell to add the driver to jars
  lineinfile: dest=/home/vagrant/.bashrc  line='alias cqlsh="cqlsh {{ vagrant_ip }}"'

